Vagrant.configure("2") do |config|
  config.vm.synced_folder "./shared", "/vagrant_shared"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 2
  end

  config.vm.define "kbarbryS" do |server|
    server.vm.hostname = "kbarbryS"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "kbarbryS"
    end

    server.vm.box = "bento/debian-12"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provision "shell", path: "./scripts/server.sh", args: ['192.168.56.110']
  end

  config.vm.define "kbarbrySW" do |worker|
    worker.vm.hostname = "kbarbrySW"
    worker.vm.provider "virtualbox" do |vb|
      vb.name = "kbarbrySW"
    end

    worker.vm.box = "bento/debian-12"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.provision "shell", path: "./scripts/worker.sh", args: ['192.168.56.110']
  end
end
