Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.define "tests-k3d" do |server|
    server.vm.hostname = "tests-k3d"
    server.vm.network "private_network", type: "dhcp"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "tests-k3d"
    end

    server.vm.box = "bento/debian-12"
    server.vm.provision "shell", path: "./scripts/server.sh"
  end
end
