Vagrant.configure("2") do |config|
  # config.vm.synced_folder "./confs", "/vagrant_shared"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.define "tests-k3d" do |server|
    server.vm.hostname = "tests-k3d"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "tests-k3d"
    end

    server.vm.box = "codeup/Ubuntu-20.04-GUI"
    server.vm.network "private_network", ip: "192.168.42.42"
    server.vm.provision "shell", path: "./scripts/server.sh"
  end
end
